### PR TITLE
Added Room and House class, and Unit Testing for both

### PR DESCRIPTION
**Pull request by lukewegryn**
Please review this code and make sure it looks good. I compiled it and ran it and everything works as expected. Please look at my unit testing so that you can see how the Room and House class integrates with the device API.

### CODE REVIEW

**Comment by ibalajiarun** [comment]
What is the purpose of Room and House class? It seems that you are creating a new list of them.

**Comment by lukewegryn** [comment]
The purpose of the House and Room class is to encapsulate the devices in a way that is easy to access and display and help with the invalidation process. Like we talked about last night, the phone will have a local copy of the current state of the House, Rooms, and Devices. When we receive an invalidation notification from the server, we make a get request that return a list of devices that have changed their status (physical light switch turned off for example). We then call the Room class method "UpdateDevice" on each of the devices that the server gave us and pass the updated device that we can query via the Device API. After all of the device ID's that the server sent us have been updated, we will have a local copy that matches the actual status of the house.

**Comment by lukewegryn** [comment]
In addition, when a user adds a device they also have the option of adding it to a specific room. This is easily done by calling "addDevice" method in the Room class once the device has been added via the DeviceAPI.

**Comment by ibalajiarun** [comment]
We might have to make some changes, but it is ok for now.

**Pull request merged**
